# Generated by Django 5.1.2 on 2024-10-20 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_resgate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('porte_coleta', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('porte_coleta', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('data_inicial', models.DateField(auto_now_add=True)),
                ('data_final', models.DateField(auto_now=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.endereco')),
            ],
        ),
    ]
