# Generated by Django 5.1.2 on 2024-10-21 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cesta', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('cpf', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('data_disponivel', models.DateField(auto_now_add=True)),
                ('data_resgate', models.DateField(auto_now=True)),
                ('descarte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendente.descarte')),
            ],
        ),
    ]
