# Generated by Django 5.1.2 on 2024-11-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0002_resgate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontosColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('numero', models.CharField(max_length=5)),
            ],
        ),
    ]
