# Generated by Django 5.1.2 on 2024-11-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0003_pontoscoleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoscoleta',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
