# Generated by Django 5.1.2 on 2024-11-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0005_pontoscoleta_bairro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chamado',
        ),
    ]
