# Generated by Django 5.1.2 on 2024-11-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0007_remove_resgate_descarte_alter_resgate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarte',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
