# Generated by Django 5.1.2 on 2024-10-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('numero', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(max_length=255)),
                ('nome_solicitante', models.CharField(max_length=255)),
                ('cpf_solicitante', models.CharField(max_length=11)),
                ('numero_contato', models.CharField(max_length=12)),
                ('email_solicitante', models.EmailField(max_length=254)),
                ('status', models.BooleanField()),
                ('foto_coleta', models.FileField(upload_to='')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.endereco')),
            ],
        ),
    ]
