# Generated by Django 5.1.2 on 2024-10-19 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('status', models.BooleanField()),
                ('quantidade', models.IntegerField()),
                ('tipo_da_cesta', models.CharField(max_length=1)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.solicitacao')),
            ],
        ),
    ]
