# Generated by Django 5.1.2 on 2024-10-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_resgate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resgate',
        ),
    ]
