# Generated by Django 5.1.2 on 2024-10-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_delete_resgate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='foto_coleta',
            field=models.ImageField(upload_to=''),
        ),
    ]
