# Generated by Django 5.1.2 on 2024-11-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_solicitacao_foto_coleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
