# Generated by Django 5.1.2 on 2024-11-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_solicitacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='equipe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
