# Generated by Django 5.1.2 on 2024-11-02 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0004_alter_solicitacao_foto_coleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('data_inicial', models.DateField(auto_now_add=True)),
                ('data_final', models.DateField(auto_now=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.solicitacao')),
            ],
        ),
    ]
