# Generated by Django 5.1.2 on 2024-11-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_solicitacao_status'),
        ('equipe_coleta', '0002_alter_chamadocoleta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadocoleta',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='cliente.solicitacao'),
        ),
    ]
