# Generated by Django 5.1.2 on 2024-11-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_coleta', '0003_alter_chamadocoleta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadocoleta',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
